### ISSUE TITLE
📃 작업 현황 보고

### ISSUE THREAD

**Issue by B0X12** [foodage/server#10]
### 🖊 업무 보고
> 작업한 내용을 아래 규격에 맞춰 작성해주세요.

🗓 **작업일 (일/주단위)**
- 메인
  - `완료` 서브 #n  ✅     // 완료된 job에 대해서는 체크 표시
  - `80%` 서브 #n         // #n에는 관련 이슈 넘버 작성
     > 도움이 필요합니다. @B0X12 
  - `20%` 서브 #n
     > 진행중 ~한 문제가 발생하여 해결 진행중입니다.

**Comment by B0X12** [comment]
🗓 **23-11-20**

- Jasypt 적용
   - `완료` application.yml DB 암호에 Jasypt 적용 #9 ✅
- Docker 배포 테스트
   - `완료` 시작/중지 쉘 스크립트 작성 #8 ✅
   - `95%` Dockerfile 작성 #8
   - `60%` 로컬에서 도커 실행 테스트

**Comment by B0X12** [comment]
🗓 **24-01-17**

- Docker 배포
   - `완료` EC2 인스턴스 결제 ✅
   - `완료` Docker 배포 관련 파일 이동 ✅
   - `완료` Docker 실행 테스트, 정상 동작 테스트 ✅
   - `완료` Spring Security 설정 상태 확인 ✅
   - `완료` 연동 정보 정리 및 공유 ✅
- [Oauth] Kakao API 연동
   - `완료` Kakao Login 개발 진행 ✅
   - `완료` 프론트엔드 연동 테스트 ✅
- [Oauth] Naver API 연동
   - `30%` Naver Login 규격 분석중
- 리팩토링
   - `40%` 코드 리팩토링, 패키지 구조 개선 작업
       -> Naver API 연동 후 develop merge 완료되면, 1~2주간 기술부채 점검 및 전체 개선 예정

**Comment by jjjaehoon** [comment]
🗓 **24-01-17**

- JWT 구현
   - `완료` JWT 인증 구조 분석 ✅
   - `완료` JWT 기능 구현 ✅
   - `10%` Refresh Token 탈취 문제에 대한 해결 방법 고안 (진행중)
   - `0%` Refresh Token 구현 (진행중)
   - `0%` Oauth & 회원가입 API에 연동 (진행중)
- Spring Security 연동
   - `완료` Spring Security3 구조 분석 진행 ✅
   - `완료` Spring Secuirty3 구현 및 테스트용 API 작성 ✅
   - `완료` 로컬 환경에서의 인가 상태 정상 동작 테스트 ✅
   - `30%` 배포 환경에서의 인가 상태 정상 동작 테스트 (진행중)
- 리팩토링
   - `40%` 불필요한 lombok 어노테이션 제거 작업 (진행중)
       -> Naver API 연동 후 develop merge 완료되면, 1~2주간 기술부채 점검 및 전체 개선 예정

**Comment by B0X12** [comment]
노션 데이터베이스로 작업현황 관리 툴이 변경되어,
해당 이슈는 종료처리합니다.
